spring.datasource.url=jdbc:mysql://localhost:3306/lost_found
spring.datasource.username=root
spring.datasource.password=Vaibhav@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB